Updates compatibility for PHP versions higher than 8xx
The error below is caused in PHP 8xx versions

Fatal error: Uncaught TypeError: Unsupported operand types: string * int in /ABCD2/www/htdocs/central/dataentry/fmt.php:1120 Stack trace: #0 {main} thrown in /ABCD2/www/htdocs/central/dataentry/fmt.php on line 1120

To correct it was changed where it says:

$tag=trim(substr($linea,0,4))*1;

To:

$tag=(int)trim(substr($linea,0,4))*(int)1;